name: Build & push docker image

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: checkout code
        uses: actions/checkout@v4

      - name: set up qemu
        uses: docker/setup-qemu-action@v2

      - name: set up buildx
        uses: docker/setup-buildx-action@v2
        
      - name: login to github container registry
        if: ${{ github.event_name == 'push' }}
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ secrets.GH_REGISTRY_USERNAME }}
          password: ${{ secrets.GITHUB_TOKEN }}
          
      - name: login to docker hub
        if: ${{ github.event_name == 'push' }}
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_REGISTRY_USERNAME }}
          password: ${{ secrets.DOCKER_REGISTRY_TOKEN }}
          
      - name: docker meta
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: |
            dotwee/alsa2mqtt
            ghcr.io/dotwee/alsa2mqtt
          flavor: |
            latest=${{ github.event_name == 'push' }}
          tags: |
            type=raw,value=${{ github.sha }}
          labels: |
            maintainer=Lukas Wolfsteiner <lukas@wolfsteiner.media>
            org.opencontainers.image.title=alsa2mqtt
            org.opencontainers.image.source=https://github.com/dotWee/docker-alsa2mqtt

      - name: build docker image
        uses: docker/build-push-action@v4
        with:
          context: .
          platforms: linux/amd64,linux/arm64,linux/arm/v7
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          push: ${{ github.event_name == 'push' }}
