name: Update Docker Hub description

on:
  push:
    paths:
      - 'README.md'
      - '.github/workflows/update-dockerhub-description.yml'
  workflow_dispatch:

jobs:
  update:
    name: Update Docker Hub description
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: update docker hub repository description
        uses: peter-evans/dockerhub-description@v3
        with:
          username: ${{ secrets.DOCKER_REGISTRY_USERNAME }}
          password: ${{ secrets.DOCKER_REGISTRY_TOKEN }}
          repository: dotwee/alsa2mqtt
